In [1]:
import numpy as np

In [2]:
mumbai=np.array([[1],[0],[0],[0],[0],[0]])
delhi=np.array([[0],[1],[0],[0],[0],[0]])
marathi=np.array([[0],[0],[1],[0],[0],[0]])
hindi=np.array([[0],[0],[0],[1],[0],[0]])
india =np.array([[0],[0],[0],[0],[1],[0]])
maharashtra=np.array([[0],[0],[0],[0],[0],[1]])
x1=np.append(mumbai, marathi, axis=1)
x2=np.sum(x1,axis=1,keepdims=True)/2
x3=np.append(delhi, hindi, axis=1)
x4=np.sum(x3,axis=1,keepdims=True)/2
x=np.append(x2, x4, axis=1)
y=np.append(maharashtra, india, axis=1)

In [3]:
x
#context words : mumbai marathi delhi hindi
#target words : maharashtra maharashtra india india

array([[0.5, 0. ],
       [0. , 0.5],
       [0.5, 0. ],
       [0. , 0.5],
       [0. , 0. ],
       [0. , 0. ]])

In [4]:
y

array([[0, 0],
       [0, 0],
       [0, 0],
       [0, 0],
       [0, 1],
       [1, 0]])

In [5]:
dims=2

In [6]:
V=mumbai.shape[0]

In [7]:
np.random.seed(0)

In [8]:
W0=np.random.uniform(low=0, high=0.8, size=(V,dims))
W1=np.random.uniform(low=0, high=0.8, size=(dims,V))

In [9]:
W0

array([[0.4390508 , 0.57215149],
       [0.4822107 , 0.43590655],
       [0.33892384, 0.51671529],
       [0.35006977, 0.7134184 ],
       [0.77093021, 0.30675322],
       [0.63338003, 0.42311594]])

In [10]:
W1

array([[0.45443565, 0.74047731, 0.05682885, 0.06970344, 0.01617472,
        0.66609588],
       [0.6225254 , 0.69600972, 0.78289467, 0.63932685, 0.36918349,
        0.62442334]])

In [22]:
def softmax(z):
    e_z = np.exp(z)
    sum_e_z = np.sum(e_z,axis=0,keepdims=True)
    return e_z/sum_e_z

In [23]:
def forward(W0,W1,x):
    h=np.dot(W0.T,x)
    v=np.dot(W1.T,h)
    return h,softmax(v)

In [24]:
def compute_cost(y, yhat):
    m=y.shape[1]
    logprobs = np.multiply(np.log(yhat),y)
    cost = - (1/m) * np.sum(logprobs)
    cost = np.squeeze(cost)
    return cost

In [25]:
def backprop(W0,W1,x,y_true,alpha):
    iter=0
    while iter<500:
        
       h,y_pred=forward(W0,W1,x)
       loss = compute_cost(y_true, y_pred)
       l1 = np.dot(W1 ,(y_pred - y_true))
       dW1 = np.dot(h,(y_pred - y_true).T)
       dW0 = np.dot(x,l1.T)
       W1 -= alpha * dW1
       W0 -= alpha * dW0
       
       if iter % 10 == 0:
            print(f"loss at iteration {iter} is {loss}")
       iter=iter+1
    
    return W0,W1

In [26]:
W0,W1=backprop(W0,W1,x,y,0.03)

loss at iteration 0 is 0.011883673729584782
loss at iteration 10 is 0.011484286998021793
loss at iteration 20 is 0.011108673020306475
loss at iteration 30 is 0.010754850799269102
loss at iteration 40 is 0.010421048383016093
loss at iteration 50 is 0.010105676449793538
loss at iteration 60 is 0.009807305749606615
loss at iteration 70 is 0.009524647767830718
loss at iteration 80 is 0.009256538091704338
loss at iteration 90 is 0.009001922053239022
loss at iteration 100 is 0.008759842296665203
loss at iteration 110 is 0.008529427978856724
loss at iteration 120 is 0.008309885360188349
loss at iteration 130 is 0.008100489583285013
loss at iteration 140 is 0.007900577469886268
loss at iteration 150 is 0.007709541193025536
loss at iteration 160 is 0.007526822703990525
loss at iteration 170 is 0.007351908811996679
loss at iteration 180 is 0.007184326829866241
loss at iteration 190 is 0.007023640711830457
loss at iteration 200 is 0.0068694476203164205
loss at iteration 210 is 0.00672137486760173

In [15]:
_,output=forward(W0,W1,delhi)
print(output)

[[0.00274685]
 [0.00246943]
 [0.00403532]
 [0.00349176]
 [0.97936393]
 [0.00789272]]


In [16]:
emb=(W0+W1.T)/2
emb.shape

(6, 2)

In [17]:
mumbai=emb[0,:]
delhi=emb[1,:]
marathi=emb[2,:]
hindi=emb[3,:]
india =emb[4,:]
maharashtra=emb[5,:]

In [18]:
def cosine_similarity(A, B):
    dot = np.dot(A,B)  
    norma = np.linalg.norm(A)
    normb = np.linalg.norm(B)
    cos = dot/(norma*normb)
    return cos

In [21]:
cosine_similarity(marathi, mumbai)

0.993002659263361